### PR TITLE
Moving kappa files

### PR DESCRIPTION
**Pull request by MalinSpaniol**
include all changed/edited kappa_labled result files and kappa_agreement files computed by kappa_agreement.py into master

### CODE REVIEW

**Comment by k47ha** [comment]
I thought we agreed on not using the report?
Why is there this long kappa_result.md file?
It is very crowded, invcludes all warnings and does not give an overview.

**Comment by MalinSpaniol** [comment]
> I thought we agreed on not using the report?
> Why is there this long kappa_result.md file?
> It is very crowded, invcludes all warnings and does not give an overview.

I thought it would be good to have all results of this anyways, and even if it is only for the final report (to include the values and say that they do not make sense in our case). I wanted to store this work somewhere, but I can also keep it in a private place

**Comment by k47ha** [comment]
It is very crowded if even the errors are in the document.
It should also maybe only include the value from the table that we know what it means.

Also there is already a write_to_file method
https://asparagus.readthedocs.io/en/latest/api/kappa_agreement.html

**Comment by MalinSpaniol** [comment]
the markdown file is taken out now - can please someone review and merge? thank you!

**Pull request merged**
